---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner
  labels:
    app: gitlab-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner
  template:
    metadata:
      labels:
        app: gitlab-runner
      annotations:
        vault.hashicorp.com/agent-inject-template-config.template.toml: |      
            [runners.kubernetes]
              helper_image = "gitlab/gitlab-runner-helper:alpine-latest-x86_64-v16.10.0"
          {{- end }}
      containers:
      - name: gitlab-runner
        image: gitlab/gitlab-runner:alpine-v16.3.1