---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio

spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2024-03-26T22-10-45Z@sha256:88af73451c7981406c1477d9fb99543be3ef2d8aea847fcf8667a38c323f217c
      - name: minio-init
        image: "minio/mc:RELEASE.2023-12-29T20-15-29Z@sha256:aec83b55bc7949223395c5a7fad3673362cb45c28eea0596f560abe947e3547b"