---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio

spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2023-12-23T07-19-11Z@sha256:47d5b01cc3020efa39aac112a7cbc919af5fb18f9ebc63bda31683590715c42b
      - name: minio-init
        image: "minio/mc:RELEASE.2024-03-25T16-41-14Z@sha256:4d8a3baba010a721510be53ad35e81cd2caa40c4f6c078fa8fd93568901c40bd"